env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - simple-import-sort
rules:
  sort-imports: 0
  import/order: 0
  simple-import-sort/sort: 2
  react/react-in-jsx-scope: 0
