title: SpaceSheep
email: sheep16@gmail.com
tagline: Bring your programming skills to the real world
description: >-
  Advance your programming skills beyond that one "hello world" program.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spacesheep.dev"
twitter_username: sheepsixteen
github_username: sheepsixteen

lang: en_UK

# Using github-flavoured common mark as markdown plugin
markdown: CommonMarkGhPages

# No theme
theme:

plugins:
  - jekyll-feed
  - jekyll-external-links
  - jekyll-gist
  - jekyll-seo-tag

# External links config
# Add the svg after links which have an external href
external_links:
  selector: 'a'
  ignored_selectors:
    - a[href*=travis]
    - a[href*=coverity]
    - a[href*=codecov]
  marker_html: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M10.604 1h4.146a.25.25 0 01.25.25v4.146a.25.25 0 01-.427.177L13.03 4.03 9.28 7.78a.75.75 0 01-1.06-1.06l3.75-3.75-1.543-1.543A.25.25 0 0110.604 1zM3.75 2A1.75 1.75 0 002 3.75v8.5c0 .966.784 1.75 1.75 1.75h8.5A1.75 1.75 0 0014 12.25v-3.5a.75.75 0 00-1.5 0v3.5a.25.25 0 01-.25.25h-8.5a.25.25 0 01-.25-.25v-8.5a.25.25 0 01.25-.25h3.5a.75.75 0 000-1.5h-3.5z"></path></svg>
